### ISSUE TITLE
core analysis taxa name mismatch

### ISSUE THREAD

**Issue by rachaelantwis** [microbiome/microbiome#68] opened 2018-02-22 15:21 UTC
Hi again!

I'm just working on another dataset and I'm getting a new problem as follows:

library(microbiome)
library(RColorBrewer)

pseq <- merged.raw
meta <- meta(pseq)
taxonomy <- tax_table(pseq)

pseq.rel <- microbiome::transform(merged.raw, "compositional")
core.taxa.standard <- core_members(pseq.rel, detection = 0.001, prevalence = 95/100)
core.taxa.standard
tax_table(pseq.rel) #to get names
pseq.core <- core(pseq.rel, detection = 0.001, prevalence = .95) #makes phyloseq if needed
core.taxa <- taxa(pseq.core)
#total core abundance in each sample
core.abundance <- sample_sums(core(pseq.rel, detection = 0.001, prevalence = .95))
core.abundance
write.table(as.data.frame(core.abundance), file="core.abundance.txt")

# Set different detection levels and prevalence
prevalences <- seq(.05, 1, .05) #95% prevalence
detections <- 10^seq(log10(1e-3), log10(.2), length = 10) 

p <- plot_core(pseq.core, plot.type = "heatmap", colours = rev(brewer.pal(5, "Spectral")),
+                min.prevalence = 0.1, prevalences = prevalences, detections = detections) +
+     xlab("Detection Threshold (Relative Abundance (%))")

I get the following error:
Error in names(df) <- c("Taxa", "DetectionThreshold", "Prevalence") : 
  'names' attribute [3] must be the same length as the vector [2]

I think it's something to do with pseq.rel having an extra taxa row?
> colnames(tax_table(pseq.rel)) 
[1] "Kingdom" "Phylum"  "Class"   "Order"   "Family"  "Genus"   "Species" "OTU"    
> colnames(tax_table(pseq.core)) 
[1] "Kingdom" "Phylum"  "Class"   "Order"   "Family"  "Genus"   "Species"
> colnames(tax_table(merged.raw))
[1] "Kingdom" "Phylum"  "Class"   "Order"   "Family"  "Genus"   "Species"

I'd be grateful for any help.

Many thanks in advance

**Comment by microsud** [comment] 2018-02-22 15:25
@rachaelantwis What is the output stored in core.taxa.standard? do you see taxa assigned?

**Comment by rachaelantwis** [comment] 2018-02-22 15:26
Yes (I think this is what you mean?):
> core.taxa.standard
 [1] "SV 1"   "SV 5"   "SV 6"   "SV 7"   "SV 10"  "SV 12"  "SV 15"  "SV 16"  "SV 17"  "SV 20"  "SV 21"  "SV 27"  "SV 30"  "SV 33"  "SV 34" 
[16] "SV 37"  "SV 44"  "SV 49"  "SV 52"  "SV 57"  "SV 72"  "SV 88"  "SV 90"  "SV 149"

**Comment by microsud** [comment] 2018-02-22 15:31
Try changing 
detections <- 10^seq(log10(1e-3), log10(.2), length = 10) 
to 
detections <- 10^seq(log10(1e-6), log10(.2), length = 10) 
and check?
Or
is it possible for you to share the pseq object save as *.rds? Can you remove the metadata information and just send the phyloseq object with taxa_table and otu_table? or just a small example data?
to sudarshan.shetty@wur.nl

cheers,
Sudarshan

**Comment by rachaelantwis** [comment] 2018-02-22 15:33
Hi - thanks but it didn't work. Happy to share the object, just not sure how to export it. Do you have some code? Many thanks :)

**Comment by microsud** [comment] 2018-02-22 15:47
saveRDS(pseq, "pseq.rds")

**Comment by rachaelantwis** [comment] 2018-02-22 16:01
Ah ok - very simple then! I'll email it over now :)
Thanks

**Comment by microsud** [comment] 2018-02-22 16:28
I cannot reproduce the error and get output as expected. I will keep this issue open for the moment and if we figure it out, the information can be shared here for others.

Cheers,
Sudarshan

**Comment by antagomir** [comment] 2018-05-20 17:20
I'm closing this for now. We can reopen if a reprocible example is found and can be fixed.

**Closed by antagomir** 2018-05-20 17:20 UTC
