### ISSUE TITLE
Struggling with merge options in microbiome package

### ISSUE THREAD

**Issue by as703** [microbiome/microbiome#90] opened 2018-09-04 00:48 UTC
Hi,

I'd be grateful for some input on two errors I'm struggling with in the microbiome package, both to do with merging taxa.

1) at the genus level, some of my OTUs are designated Coproccus_1 or Coproccus_2 and so on. Same for Ruminococcus. I don't need this level of detail and would like to merge to a single Coprococcus or Ruminococcus genus. I'm trying to use merge_taxa2:

ps.merged <- merge_taxa2(ps, pattern="^Ruminococcus", name="Ruminococcus")

But I get the error: Error in mytaxa[[1]] : subscript out of bounds.

I'm sure my syntax is wrong but I can't find to many examples to work from. If anyone can point me in the right direction I'd be grateful.

2) I'm trying to use aggregate_taxa to agglomerate and select the top 10 Families:

ps.family <- aggregate_taxa(ps, "Family", top = 10) 

But I get the error: Error in validObject(.Object) : invalid class “otu_table” object: 
 Non-numeric matrix provided as OTU table.
Abundance is expected to be numeric.

The OTU table looks entirely normal to me and tax_glom works absolutely fine:

ps.family <- tax_glom(ps.comp, "Family", NArm=TRUE) 
ps.family.abundance <- psmelt(ps.family) %>%
  top_n(10, Abundance)

Again, if anyone can see where I'm going wrong I'd be grateful.

Many thanks in advance for your help.

**Comment by antagomir** [comment] 2018-09-06 20:30
Thanks! I cannot reproduce either issue with example data sets and this makes it difficult help. Could you either provide a reproducible example with one of our example data sets from the package, or send me a small example data set of your own, together with a code that reproduces an error. Can send by email.

**Comment by biobee** [comment] 2019-05-09 15:24
I had the exact same issue for several months, also with v.1.4.2. After updating via Bioconductor 3.9 to microbiome v 1.6.0 it all works fine. Thanks for the updates :-)

**Comment by antagomir** [comment] 2019-05-09 18:33
Ok, great. Seems like a version issue. Closing this now, we can reopen if it persists.

**Closed by antagomir** 2019-05-09 18:33 UTC
