### ISSUE TITLE
plot_composition() error on a std phyloseq object

### ISSUE THREAD

**Issue by wolass** [microbiome/microbiome#2] opened 2015-10-29 09:41 UTC
I cannot use the plot_composition() function because it trows an error:

    Error in sample_data(data.frame(x)[i, j, drop = FALSE]) : 
    error in evaluating the argument 'object' in selecting a method for function 'sample_data': Error in   `[.data.frame`(data.frame(x), i, j, drop = FALSE) : 
    undefined columns selected

Everything works fine if I use the plot_bar() function from the phyloseq package. 

    > sessionInfo ()
    R version 3.2.2 (2015-08-14)
    Platform: x86_64-pc-linux-gnu (64-bit)
    Running under: Ubuntu 14.04.3 LTS

    locale:
    [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=pl_PL.UTF-8            LC_COLLATE=en_US.UTF-8    
    [5] LC_MONETARY=pl_PL.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=pl_PL.UTF-8       LC_NAME=C                 
    [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=pl_PL.UTF-8 LC_IDENTIFICATION=C       

    attached base packages:
    [1] parallel  grid      stats     graphics  grDevices utils     datasets  methods   base     

    other attached packages:
    [1] microbiome_0.99.62  RPA_1.26.0          affy_1.48.0         Biobase_2.30.0          BiocGenerics_0.16.0 plyr_1.8.3         
    [7] dplyr_0.4.3         ggplot2_1.0.1       tidyr_0.3.1         phyloseq_1.14.0

**Comment by antagomir** [comment] 2015-10-30 00:05
Thanks ! I can't reproduce your bug. The example at https://github.com/microbiome/microbiome/blob/master/vignettes/Composition.md works fine. Could you send me an example phyloseq object by email for instance so I can check ?

**Comment by antagomir** [comment] 2015-10-30 12:58
Ok should be fixed now in the latest version. Tnx !

**Closed by antagomir** 2015-10-30 12:58 UTC
