### ISSUE TITLE
Summarize function

### ISSUE THREAD

**Issue by microsud** [microbiome/microbiome#63] opened 2017-11-13 22:03 UTC
'summarize_phyloseq' object to give like 'biom' summary. 
1. Total number of reads,
2. Average number of reads,
3. Minimum library size,
4. Maximum library size,
5. Percent classification of OTUs to various taxonomic levels,
6. Normality test for library size,
7. Number of singletons.

**Comment by antagomir** [comment] 2017-11-13 22:25
Great !

**Comment by antagomir** [comment] 2018-05-20 17:33
This now seems to be in R folder, so we could almost close this issue. 

But could you add an example or examples of this function in the tutorials? This can be done by modifying a suitable Rmd file in the gh-pages branch, or adding a new Rmd file and linking it from index.Rmd

**Comment by microsud** [comment] 2018-05-21 11:46
Example added to [Data manipulation section](http://microbiome.github.io/microbiome/Preprocessing.html) of tutorials.

**Comment by memoll** [comment] 2019-07-26 19:12
Hi! 

The "percent of OTUs that are singletons" I get using the summarize_phyloseq() seems to be a lot!! Are you sure about the way you calculate it, which is : length(taxa_sums(x)[taxa_sums(x) <= 1])/nrow(otu_table(x)) * 100)
How about: length(taxa_sums(x)[taxa_sums(x) <= 1])/ntaxa(x) * 100 ?

**Comment by antagomir** [comment] 2019-07-26 19:35
Thanks. This was written by someone else but as far as I can see, replacing nrow(otu_table(x)) with ntaxa(x) would not change the results since they essentially calculate the same thing (otu_table(x) is taxa x samples matrix and hence nrow of it is the same than ntaxa..). 

However I notice the following:
- High number of singletons could be due to the fact that this function calculates not only singletons but also taxa with zero sum i.e. taxa_sums(x) <= 1 instead of taxa_sums(x) == 1. I think it would be more clear to switch to the latter here. Or is this intended @microsud ?

- I seems to me that the same percentage can calculated with a shorter expression, which is probably faster and perhaps more intuitive to read: mean(taxa_sums(x) == 1) * 100 

- Therefore I propose to replace this calculation with mean(taxa_sums(x) == 1) * 100 and I think that might solve the reported issue.

**Comment by antagomir** [comment] 2019-07-26 19:43
Thanks. This was written by someone else but as far as I can see, replacing nrow(otu_table(x)) with ntaxa(x) would not change the results since they essentially calculate the same thing (otu_table(x) is taxa x samples matrix and hence nrow of it is the same than ntaxa..). 

However I notice the following:
- High number of singletons could be due to the fact that this function calculates not only singletons but also taxa with zero sum i.e. taxa_sums(x) <= 1 instead of taxa_sums(x) == 1. I think it would be more clear to switch to the latter here. Or is this intended @microsud ?

- I seems to me that the same percentage can calculated with a shorter expression, which is probably faster and perhaps more intuitive to read: mean(taxa_sums(x) == 1) * 100 

- Therefore I propose to replace this calculation with mean(taxa_sums(x) == 1) * 100 and I think that might solve the reported issue. 

- I also suggest that the function will return the variables as a list unless there are reasons not to do so. Returning values explicitly is good practice.

Will make a PR shortly. 

p.s. I replaced "cat" commands by "message" (see recommendations in R Extensions).

**Comment by memoll** [comment] 2019-07-26 20:37
Thanks for the quick answer! 
Ok I see, rownames of my otu_table() are my sample names. Even when I use the taxa_are_rows argument, it doesn't change my result. I have to work on that! Anyways, now I see why nsamples() was the solution for me instead of ntaxa(). 

Also, thanks for the other suggestions and have a great weekend!
Mona

**Comment by antagomir** [comment] 2019-07-26 20:48
Interesting! Ok in that sense ntaxa might be less error prone in fact. However otu_table with taxa_are_rows = TRUE should do the trick. If you have a reproducible example that might be useful to check and then fix if possible.

However, my proposed solution above `mean(taxa_sums(x) == 1) * 100` should work regardless of those issues. I will now merge the change. Could you test?

**Closed by antagomir** 2019-07-26 20:48 UTC
Labels: Feature, documentation

**Comment by memoll** [comment] 2019-07-27 02:45
It works! thanks :)
